### ISSUE TITLE
fix volume mount for elasticsearch-tls-certs

### ISSUE THREAD

**Issue by glotzerhotze** [sysdiglabs/integrations-charts#24]
https://github.com/sysdiglabs/integrations-charts/blob/d942d53c203fe450774987889f602b30e74923e5/charts/elasticsearch-exporter/templates/deployment.yaml#L101

this should be changed from `secretTLS` to `secretName`

**Comment by glotzerhotze** [comment]
there is a pull-request to fix this issue [here](https://github.com/sysdiglabs/integrations-charts/pull/25)

**Comment by glotzerhotze** [comment]
So let me explain some more details of the issues I have with the current code on main branch:

1. the above mentioned key name is wrong. thus the manifest won't apply and the whole deployment fails.
2. mounting the ES-root-CA certificate into the pod and NOT using them - aka. running with `--es.ssl-skip-verify` defeats the purpose of mounting the certificate in the first place.
3. the current README does advise to mount the ES-root-CA **private key** into the pod - this is a big security no-go, as the root-CA key is only needed so self-sign the root-CA certificate, which is here needed to verify the TLS certificates the actual ES endpoint will present when connecting to it.
4. Instead of the ES-root-CA **private key**, mounting a **client certificate and corresponding private key** does make more sense, if you want mutual TLS for the whole connection. these things need to be pre-generated though in case one would use the ECK-operator with custom certificates, for example. BUT the fact that there is no configuration to actually use client-side certificate authentication when asking the ES endpoints for metrics again defeats the purpose of having all this in the first place.
5. it would be much easier if you would stay in line with the naming-convention that ECK has chosen for naming certificates (aka. ca.crt vs. root-ca.crt - also the PEM formated file is NOT needed here) - this would allow to re-use the existing secrets that need to be present pre-initialising an ES cluster via ECK-operator with custom PKI configuration
6. in the values-file, there is a sane default setting missing for `image.pullPolicy` - again, the manifest won't validate

Regarding TLS and given the above points, I think you could actually get away with using TLS without having to setup certificates in the exporter AT ALL, as the only one you actually need (ES root-CA certificate) already comes with an TLS enabled ES cluster in one form or another. This should be re-used ideally.

On the other hand it would be nice to actually USE the CA cert to at least verify the chain-of-trust for the server-TLS-certificate that the ES-endpoint being queried will present. This is currently disabled, but works quite well if you tweak the deployment accordingly.

For the validation errors - well, bumper.

**Steps to reproduce the above issues:**

1. add the official repo for these charts to helm v3
2. update charts to be on the latest version - for me this is currently `elasticsearch-exporter-0.2.1`
3. create the required URL secret with username and password for the ES endpoint
4. render the manifest via helm using the following command: 
```
helm template elasticsearch-exporter-data-es-default-deploy promcat-charts/elasticsearch-exporter \
  --set namespaceName="data" \
  --set workloadType="statefulset" \
  --set workloadName="exres-es-default" \
  --set secretURL="exres-es-url" \
  --set secretTLS="exres-es-tls" \
  --set tlsmode="true" \
  --set image.pullPolicy="IfNotPresent"
```
5. check the namespace for the created manifest - it's probably `default`, but should be the one I set above - using `namespace: {{ .Values.namespaceName }}` vs `namespace: {{ .Release.Namespace }}` maybe? 
at least make people aware in the documentation that the current configuration will implicitly work across namespaces - in case people want to run the exporter along-side the ES cluster in the SAME namespace as the ES cluster itself.

I managed to work around all the above issues and can successfully scrape metrics with the exporter.

Since you closed a PR already, let me know if you are interested to fix the above issues and how to go about fixing them ideally. I'd be more than happy to help out and submit more code if you want me to.

Thank you.

**Comment by daviddetorres** [comment]
Thanks for the detailed explanation. Let us reproduce the problem and evaluate the solution. We will get back to you with a solution.

**Comment by glotzerhotze** [comment]
I already have a working solution - thus the question if you are interested in more PR's. But if you just close them, I'd rather spent my time elsewhere, as making this work already took quite some time - and that's the only resource I don't have enough of.

**Comment by Dlorite** [comment]
Your last PR was about the old chart that is why we close it. If you have the fix already, I will review it asap and we apreciate a lot what you did.

**Comment by Dlorite** [comment]
For the point 5, the thing is you have to render it with helm template -n My-Namespace ... so the release namespace is written it there namespace: {{ .Release.Namespace }}

**Comment by daviddetorres** [comment]
> thus the question if you are interested in more PR's. 

@glotzerhotze We really appreciate all the info that you provided us and the time that you took on it. We would like you to make a PR with your working solution, and we will review it with four eyes. 

However, if as you said you don't have enough time to make it, we can also commit on working on this and have a solution from our side.

**Comment by glotzerhotze** [comment]
Alright - I will try to submit my changes by the end of today. Please give me some time to wrap that up after work.

Thank you.

**Comment by Dlorite** [comment]
> For the point 5, the thing is you have to render it with helm template -n My-Namespace ... so the release namespace is written it there namespace: {{ .Release.Namespace }}

To explain it better,   --set namespaceName="data" this is the namespace where your elastic is running and then the -n MyNamespace is the namespace where you want to deploy the exporter
